# Generated by Django 2.0.6 on 2018-06-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=80)),
                ('school_address', models.CharField(max_length=200)),
                ('school_contact', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=80)),
                ('teacher_address', models.CharField(max_length=200)),
                ('teacher_contact', models.CharField(max_length=40)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ksude.School')),
            ],
        ),
    ]
